CREATE TABLE doctor
 (id BIGINT generated by default as identity (start with 1),
first_name varchar(255) not null,
last_name varchar(255) not null,
patronymic varchar(255),
specialization varchar(255) not null,
primary key (id))

create table patient
 (id bigint generated by default as identity (start with 1),
  first_name varchar(255) not null, last_name varchar(255) not null,
   patronymic varchar(255),
    phone_number varchar(255) not null,
     primary key (id))

create table reciept
 (id bigint generated by default as identity (start with 1),
  creation_date date not null,
description varchar(255) not null,
priority varchar(255) not null,
validity date not null,
doctor_id bigint not null,
patient_id bigint not null,
primary key (id),
foreign key (doctor_id) references doctor on delete restrict ,
 foreign key (patient_id) references patient on delete restrict );

